version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 80:8000
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PWD=${DB_PWD}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - EXPIRE_MINUTES=${EXPIRE_MINUTES}

  postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_PASSWORD=${DB_PWD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
